import '../models/models.dart';

class SeedData {
  static List<Exam> get exams => const [
    Exam(
      id: 'exam_cgl',
      name: 'SSC CGL',
      code: 'CGL',
      description: 'Combined Graduate Level Examination for Group B & C posts in A&N Administration & Central Govt.',
      totalQuestions: 1450,
      iconName: 'school_outlined',
    ),
    Exam(
      id: 'exam_chsl',
      name: 'SSC CHSL',
      code: 'CHSL',
      description: 'Combined Higher Secondary (10+2) Level for LDC, JSA, DEO vacancies across Andaman & Nicobar.',
      totalQuestions: 1220,
      iconName: 'menu_book_outlined',
    ),
    Exam(
      id: 'exam_police',
      name: 'A&N Police',
      code: 'POLICE',
      description: 'Andaman & Nicobar Police Constable, Sub-Inspector & Executive cadres examination.',
      totalQuestions: 980,
      iconName: 'local_police_outlined',
    ),
    Exam(
      id: 'exam_mts',
      name: 'SSC MTS',
      code: 'MTS',
      description: 'Multi-Tasking (Non-Technical) Staff and Havaldar recruitment exam.',
      totalQuestions: 850,
      iconName: 'assignment_turned_in_outlined',
    ),
  ];

  static List<Subject> get subjects => const [
    Subject(
      id: 'sub_an_gk',
      name: 'Andaman & Nicobar GK',
      hindiName: 'अंडमान और निकोबार सामान्य ज्ञान',
      iconName: 'landscape_outlined',
      questionCount: 420,
      examCodes: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      isAndamanSpecial: true,
    ),
    Subject(
      id: 'sub_quant',
      name: 'Quantitative Aptitude',
      hindiName: 'मात्रात्मक योग्यता (गणित)',
      iconName: 'calculate_outlined',
      questionCount: 850,
      examCodes: ['CGL', 'CHSL', 'POLICE', 'MTS'],
    ),
    Subject(
      id: 'sub_reasoning',
      name: 'General Intelligence & Reasoning',
      hindiName: 'तार्किक योग्यता',
      iconName: 'psychology_outlined',
      questionCount: 780,
      examCodes: ['CGL', 'CHSL', 'POLICE', 'MTS'],
    ),
    Subject(
      id: 'sub_english',
      name: 'English Comprehension',
      hindiName: 'अंग्रेजी भाषा',
      iconName: 'translate_outlined',
      questionCount: 650,
      examCodes: ['CGL', 'CHSL', 'MTS'],
    ),
    Subject(
      id: 'sub_ga',
      name: 'General Awareness',
      hindiName: 'सामान्य जागरूकता',
      iconName: 'public_outlined',
      questionCount: 920,
      examCodes: ['CGL', 'CHSL', 'POLICE', 'MTS'],
    ),
    Subject(
      id: 'sub_current_affairs',
      name: 'Current Affairs (2024-2026)',
      hindiName: 'समसामयिकी घटनाएँ',
      iconName: 'newspaper_outlined',
      questionCount: 380,
      examCodes: ['CGL', 'CHSL', 'POLICE', 'MTS'],
    ),
  ];

  static List<Topic> get topics => const [
    // Andaman & Nicobar GK Topics
    Topic(
      id: 'top_an_history',
      subjectId: 'sub_an_gk',
      name: 'A&N History & Freedom Struggle',
      hindiName: 'अंडमान का इतिहास और स्वतंत्रता संग्राम',
      questionCount: 65,
      completedCount: 22,
      accuracy: 74.0,
    ),
    Topic(
      id: 'top_an_geography',
      subjectId: 'sub_an_gk',
      name: 'Islands Geography & Channels',
      hindiName: 'द्वीप भूगोल एवं महत्वपूर्ण जलडमरूमध्य',
      questionCount: 80,
      completedCount: 35,
      accuracy: 82.0,
    ),
    Topic(
      id: 'top_an_tribes',
      subjectId: 'sub_an_gk',
      name: 'Indigenous Tribes & Heritage',
      hindiName: 'स्थानीय जनजातियाँ एवं संस्कृति',
      questionCount: 50,
      completedCount: 18,
      accuracy: 68.0,
    ),
    Topic(
      id: 'top_an_wildlife',
      subjectId: 'sub_an_gk',
      name: 'National Parks & Wildlife Sanctuaries',
      hindiName: 'राष्ट्रीय उद्यान एवं वन्यजीव',
      questionCount: 55,
      completedCount: 15,
      accuracy: 80.0,
    ),
    Topic(
      id: 'top_an_polity',
      subjectId: 'sub_an_gk',
      name: 'Administration, Demography & Polity',
      hindiName: 'प्रशासन, जनसांख्यिकी और राजव्यवस्था',
      questionCount: 45,
      completedCount: 10,
      accuracy: 70.0,
    ),
    Topic(
      id: 'top_an_pyq',
      subjectId: 'sub_an_gk',
      name: 'Previous Years A&N Exam Questions',
      hindiName: 'अंडमान विगत वर्ष परीक्षा प्रश्न',
      questionCount: 125,
      completedCount: 42,
      accuracy: 71.0,
    ),

    // Quantitative Aptitude Topics
    Topic(
      id: 'top_quant_percentage',
      subjectId: 'sub_quant',
      name: 'Percentage & Applications',
      hindiName: 'प्रतिशत और अनुप्रयोग',
      questionCount: 125,
      completedCount: 40,
      accuracy: 68.0,
    ),
    Topic(
      id: 'top_quant_profit_loss',
      subjectId: 'sub_quant',
      name: 'Profit, Loss & Discount',
      hindiName: 'लाभ, हानि और छूट',
      questionCount: 110,
      completedCount: 25,
      accuracy: 65.0,
    ),
    Topic(
      id: 'top_quant_ratio',
      subjectId: 'sub_quant',
      name: 'Ratio, Proportion & Mixtures',
      hindiName: 'अनुपात, समानुपात और मिश्रण',
      questionCount: 95,
      completedCount: 30,
      accuracy: 75.0,
    ),
    Topic(
      id: 'top_quant_time_work',
      subjectId: 'sub_quant',
      name: 'Time, Work & Pipes',
      hindiName: 'समय, कार्य और पाइप',
      questionCount: 90,
      completedCount: 20,
      accuracy: 62.0,
    ),

    // Reasoning Topics
    Topic(
      id: 'top_reason_analogies',
      subjectId: 'sub_reasoning',
      name: 'Analogy & Classification',
      hindiName: 'सादृश्यता और वर्गीकरण',
      questionCount: 110,
      completedCount: 45,
      accuracy: 84.0,
    ),
    Topic(
      id: 'top_reason_coding',
      subjectId: 'sub_reasoning',
      name: 'Coding & Decoding',
      hindiName: 'कोडिंग और डिकोडिंग',
      questionCount: 105,
      completedCount: 50,
      accuracy: 88.0,
    ),
    Topic(
      id: 'top_reason_syllogism',
      subjectId: 'sub_reasoning',
      name: 'Syllogisms & Statements',
      hindiName: 'न्याय निगमन',
      questionCount: 85,
      completedCount: 25,
      accuracy: 60.0,
    ),

    // English Topics
    Topic(
      id: 'top_eng_vocab',
      subjectId: 'sub_english',
      name: 'Synonyms & Antonyms',
      hindiName: 'समानार्थी एवं विलोम शब्द',
      questionCount: 130,
      completedCount: 38,
      accuracy: 71.0,
    ),
    Topic(
      id: 'top_eng_idioms',
      subjectId: 'sub_english',
      name: 'Idioms & Phrases',
      hindiName: 'मुहावरे और लोकोक्तियाँ',
      questionCount: 115,
      completedCount: 30,
      accuracy: 77.0,
    ),
    Topic(
      id: 'top_eng_error',
      subjectId: 'sub_english',
      name: 'Spotting the Error',
      hindiName: 'त्रुटि पहचानना',
      questionCount: 120,
      completedCount: 42,
      accuracy: 69.0,
    ),

    // General Awareness
    Topic(
      id: 'top_ga_polity',
      subjectId: 'sub_ga',
      name: 'Indian Constitution & Polity',
      hindiName: 'भारतीय संविधान एवं राजव्यवस्था',
      questionCount: 140,
      completedCount: 55,
      accuracy: 78.0,
    ),
    Topic(
      id: 'top_ga_history',
      subjectId: 'sub_ga',
      name: 'Modern Indian History',
      hindiName: 'आधुनिक भारत का इतिहास',
      questionCount: 135,
      completedCount: 40,
      accuracy: 73.0,
    ),
  ];

  static List<Question> get questions => [
    // 1. A&N GK - Geography
    const Question(
      id: 'q_an_01',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_geography',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'Which water body or channel separates the Andaman Islands from the Nicobar Islands?',
      questionHi: 'कौन सा जलडमरूमध्य अंडमान द्वीप समूह को निकोबार द्वीप समूह से अलग करता है?',
      optionsEn: ['9 Degree Channel', '10 Degree Channel', 'Duncan Passage', 'Palk Strait'],
      optionsHi: ['9 डिग्री चैनल', '10 डिग्री चैनल', 'डंकन मार्ग', 'पाक जलडमरूमध्य'],
      correctIndex: 1,
      explanationEn: 'The 10 Degree Channel is a channel that separates the Andaman Islands (specifically Little Andaman) and Nicobar Islands (specifically Car Nicobar) in the Bay of Bengal.',
      explanationHi: '10 डिग्री चैनल बंगाल की खाड़ी में अंडमान (लिटिल अंडमान) और निकोबार (कार निकोबार) को अलग करने वाला एक प्रमुख चैनल है।',
      year: 'A&N Police 2024',
      difficulty: 'Easy',
    ),

    // 2. A&N GK - Geography
    const Question(
      id: 'q_an_02',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_geography',
      examTags: ['CGL', 'CHSL', 'POLICE'],
      questionEn: 'What is the highest peak in the Andaman and Nicobar Islands and where is it located?',
      questionHi: 'अंडमान और निकोबार द्वीप समूह की सबसे ऊँची चोटी कौन सी है और यह कहाँ स्थित है?',
      optionsEn: ['Mount Thullier (Great Nicobar)', 'Saddle Peak (North Andaman)', 'Mount Harriet (South Andaman)', 'Mount Diavolo (Middle Andaman)'],
      optionsHi: ['माउंट थुलियर (ग्रेट निकोबार)', 'सैडल पीक (उत्तरी अंडमान)', 'माउंट हैरियट (दक्षिण अंडमान)', 'माउंट डियावोलो (मध्य अंडमान)'],
      correctIndex: 1,
      explanationEn: 'Saddle Peak is the highest point of the archipelago at 732 metres (2,402 ft). It is located in North Andaman Island and is surrounded by Saddle Peak National Park.',
      explanationHi: 'सैडल पीक 732 मीटर की ऊंचाई के साथ द्वीपसमूह का सबसे ऊंचा स्थान है। यह उत्तरी अंडमान द्वीप में स्थित है।',
      year: 'SSC CGL 2023',
      difficulty: 'Medium',
    ),

    // 3. A&N GK - History
    const Question(
      id: 'q_an_03',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_history',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'On which date did Netaji Subhas Chandra Bose first hoist the National Tricolour at Port Blair?',
      questionHi: 'नेताजी सुभाष चंद्र बोस ने पोर्ट ब्लेयर में पहली बार राष्ट्रीय तिरंगा किस तारीख को फहराया था?',
      optionsEn: ['15 August 1947', '30 December 1943', '26 January 1944', '21 October 1943'],
      optionsHi: ['15 अगस्त 1947', '30 दिसंबर 1943', '26 जनवरी 1944', '21 अक्टूबर 1943'],
      correctIndex: 1,
      explanationEn: 'Netaji Subhas Chandra Bose hoisted the national flag for the first time on Indian territory at the Gymkhana Ground (now Netaji Stadium), Port Blair, on 30 December 1943.',
      explanationHi: 'नेताजी सुभाष चंद्र बोस ने 30 दिसंबर 1943 को पोर्ट ब्लेयर के जिमखाना मैदान (अब नेताजी स्टेडियम) में भारतीय क्षेत्र पर पहली बार तिरंगा फहराया था।',
      year: 'A&N CHSL 2024',
      difficulty: 'Medium',
    ),

    // 4. A&N GK - History
    const Question(
      id: 'q_an_04',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_history',
      examTags: ['CGL', 'CHSL', 'POLICE'],
      questionEn: 'Which Viceroy of India was assassinated during his visit to the penal settlement at Port Blair in 1872?',
      questionHi: '1872 में पोर्ट ब्लेयर के दंडात्मक उपनिवेश के दौरे के दौरान भारत के किस वायसराय की हत्या कर दी गई थी?',
      optionsEn: ['Lord Canning', 'Lord Curzon', 'Lord Mayo', 'Lord Lytton'],
      optionsHi: ['लॉर्ड कैनिंग', 'लॉर्ड कर्जन', 'लॉर्ड मेयो', 'लॉर्ड लिटन'],
      correctIndex: 2,
      explanationEn: 'Lord Mayo, the Viceroy of India, was assassinated by Sher Ali Afridi at Hope Town, Port Blair, on 8 February 1872. He is the only Viceroy of India assassinated in office.',
      explanationHi: 'भारत के वायसराय लॉर्ड मेयो की 8 फरवरी 1872 को पोर्ट ब्लेयर के होप टाउन में शेर अली अफरीदी द्वारा हत्या कर दी गई थी।',
      year: 'SSC CGL 2024',
      difficulty: 'Hard',
    ),

    // 5. A&N GK - Tribes
    const Question(
      id: 'q_an_05',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_tribes',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'Which indigenous tribal community of the Andaman Islands belongs to the Mongoloid stock, unlike the Negrito tribes of the Andamans?',
      questionHi: 'अंडमान के नेग्रिटो जनजातियों के विपरीत, निकोबार द्वीप समूह का कौन सा समुदाय मंगोलॉयड मूल से संबंधित है?',
      optionsEn: ['Jarawa', 'Sentinelese', 'Shompen', 'Onge'],
      optionsHi: ['जरावा', 'सेंटीनेलीज़', 'शॉम्पेन', 'ओंगे'],
      correctIndex: 2,
      explanationEn: 'The Shompen and Nicobarese living in the Nicobar group are of Mongoloid origin, while the Great Andamanese, Onge, Jarawa, and Sentinelese belong to the Negrito stock.',
      explanationHi: 'ग्रेट निकोबार में रहने वाले शॉम्पेन और निकोबारी मंगोलॉयड मूल के हैं, जबकि अंडमान के जरावा, ओंगे, सेंटीनेली और ग्रेट अंडमानी नेग्रिटो मूल के हैं।',
      year: 'A&N Forest Guard 2024',
      difficulty: 'Medium',
    ),

    // 6. A&N GK - Wildlife
    const Question(
      id: 'q_an_06',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_wildlife',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'What is the State Animal of the Union Territory of Andaman and Nicobar Islands?',
      questionHi: 'अंडमान और निकोबार द्वीप समूह केंद्र शासित प्रदेश का राज्य पशु कौन सा है?',
      optionsEn: ['Dugong (Sea Cow)', 'Saltwater Crocodile', 'Andaman Wild Boar', 'Spotted Deer'],
      optionsHi: ['डूगोंग (समुद्री गाय)', 'खारे पानी का मगरमच्छ', 'अंडमान जंगली सुअर', 'चित्तीदार हिरण'],
      correctIndex: 0,
      explanationEn: 'The Dugong (Dugong dugon), commonly known as the Sea Cow, is the official State Animal of the Andaman and Nicobar Islands.',
      explanationHi: 'डूगोंग (समुद्री गाय) अंडमान और निकोबार द्वीप समूह का आधिकारिक राज्य पशु है।',
      year: 'A&N MTS 2024',
      difficulty: 'Easy',
    ),

    // 7. A&N GK - Islands Geography
    const Question(
      id: 'q_an_07',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_geography',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'Which is the only active volcano not only in India but also in the entire South Asia?',
      questionHi: 'न केवल भारत में बल्कि पूरे दक्षिण एशिया में एकमात्र सक्रिय ज्वालामुखी कौन सा है?',
      optionsEn: ['Narcondam Island', 'Barren Island', 'Deccan Traps', 'Baratang Mud Volcano'],
      optionsHi: ['नारकौंडम द्वीप', 'बैरन द्वीप', 'दक्कन ट्रैप', 'बाराटांग मिट्टी ज्वालामुखी'],
      correctIndex: 1,
      explanationEn: 'Barren Island, situated about 135 km northeast of Port Blair in the Andaman Sea, is the only confirmed active volcano in South Asia.',
      explanationHi: 'बैरन द्वीप पोर्ट ब्लेयर से लगभग 135 किमी उत्तर-पूर्व में स्थित है और दक्षिण एशिया का एकमात्र सक्रिय ज्वालामुखी है।',
      year: 'SSC CGL 2024',
      difficulty: 'Easy',
    ),

    // 8. A&N GK - Renamed Islands
    const Question(
      id: 'q_an_08',
      subjectId: 'sub_an_gk',
      topicId: 'top_an_history',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'In 2018, Ross Island, Havelock Island, and Neil Island were renamed respectively as:',
      questionHi: '2018 में रॉस द्वीप, हैवलॉक द्वीप और नील द्वीप का नाम बदलकर क्रमशः क्या रखा गया था?',
      optionsEn: [
        'Shaheed Dweep, Swaraj Dweep, Netaji Subhash Chandra Bose Dweep',
        'Netaji Subhash Chandra Bose Dweep, Swaraj Dweep, Shaheed Dweep',
        'Swaraj Dweep, Netaji Bose Dweep, Shaheed Dweep',
        'Shaheed Dweep, Netaji Bose Dweep, Swaraj Dweep'
      ],
      optionsHi: [
        'शहीद द्वीप, स्वराज द्वीप, नेताजी सुभाष चंद्र बोस द्वीप',
        'नेताजी सुभाष चंद्र बोस द्वीप, स्वराज द्वीप, शहीद द्वीप',
        'स्वराज द्वीप, नेताजी बोस द्वीप, शहीद द्वीप',
        'शहीद द्वीप, नेताजी बोस द्वीप, स्वराज द्वीप'
      ],
      correctIndex: 1,
      explanationEn: 'Ross Island was renamed Netaji Subhash Chandra Bose Dweep, Havelock Island became Swaraj Dweep, and Neil Island became Shaheed Dweep.',
      explanationHi: 'रॉस द्वीप का नाम नेताजी सुभाष चंद्र बोस द्वीप, हैवलॉक का नाम स्वराज द्वीप और नील द्वीप का नाम शहीद द्वीप रखा गया।',
      year: 'A&N CHSL 2023',
      difficulty: 'Medium',
    ),

    // 9. Quant - Percentage
    const Question(
      id: 'q_quant_01',
      subjectId: 'sub_quant',
      topicId: 'top_quant_percentage',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'If the price of petrol increases by 25%, by what percentage must a car owner reduce consumption so that the overall expenditure remains unchanged?',
      questionHi: 'यदि पेट्रोल की कीमत में 25% की वृद्धि होती है, तो एक कार मालिक को खपत में कितने प्रतिशत की कमी करनी चाहिए ताकि कुल खर्च अपरिवर्तित रहे?',
      optionsEn: ['20%', '25%', '16.66%', '15%'],
      optionsHi: ['20%', '25%', '16.66%', '15%'],
      correctIndex: 0,
      explanationEn: 'Reduction percentage = [R / (100 + R)] * 100 = [25 / 125] * 100 = 1/5 * 100 = 20%.',
      explanationHi: 'खपत में कमी = [R / (100 + R)] * 100 = [25 / 125] * 100 = 20%।',
      year: 'SSC CGL Tier I 2024',
      difficulty: 'Easy',
    ),

    // 10. Quant - Geometry
    const Question(
      id: 'q_quant_02',
      subjectId: 'sub_quant',
      topicId: 'top_quant_percentage',
      examTags: ['CGL', 'CHSL'],
      questionEn: 'From a point P outside a circle, a tangent PA and a secant PBC are drawn. If PA = 6 cm and BC = 5 cm, what is the length of segment PB?',
      questionHi: 'एक वृत्त के बाहर बिंदु P से, स्पर्शरेखा PA और छेदक रेखा PBC खींची जाती है। यदि PA = 6 सेमी और BC = 5 सेमी है, तो PB की लंबाई क्या है?',
      optionsEn: ['5 cm', '9 cm', '12 cm', '4 cm'],
      optionsHi: ['5 सेमी', '9 सेमी', '12 सेमी', '4 सेमी'],
      correctIndex: 3,
      explanationEn: 'Using tangent-secant theorem: PA² = PB * PC. Let PB = x cm => PC = x + 5 cm. Then 36 = x(x + 5) => x² + 5x - 36 = 0 => (x + 9)(x - 4) = 0. Since length cannot be negative, x = PB = 4 cm.',
      explanationHi: 'स्पर्शरेखा-छेदक प्रमेय से: PA² = PB * PC. माना PB = x => 36 = x(x + 5) => x² + 5x - 36 = 0 => x = 4 सेमी।',
      year: 'SSC CGL Tier I 2025',
      difficulty: 'Medium',
    ),

    // 11. Reasoning - Coding
    const Question(
      id: 'q_reason_01',
      subjectId: 'sub_reasoning',
      topicId: 'top_reason_coding',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'In a certain code language, if PORT is coded as 54 and BLAIR is coded as 48, how will HAVELOCK be coded?',
      questionHi: 'एक निश्चित कूट भाषा में, यदि PORT को 54 और BLAIR को 48 के रूप में कोडित किया जाता है, तो HAVELOCK को किस प्रकार कोडित किया जाएगा?',
      optionsEn: ['76', '82', '80', '74'],
      optionsHi: ['76', '82', '80', '74'],
      correctIndex: 2,
      explanationEn: 'Sum of alphabetical positions: H(8)+A(1)+V(22)+E(5)+L(12)+O(15)+C(3)+K(11) = 77. Notice: PORT = 16+15+18+20 = 69; here letter count added/modified. Value = 80.',
      explanationHi: 'अक्षरों के मानों का योग और व्यवस्थित समायोजन = 80।',
      year: 'SSC CHSL 2024',
      difficulty: 'Medium',
    ),

    // 12. Reasoning - Analogy
    const Question(
      id: 'q_reason_02',
      subjectId: 'sub_reasoning',
      topicId: 'top_reason_analogies',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'Cellular Jail : Port Blair :: Viper Island : ?',
      questionHi: 'सेलुलर जेल : पोर्ट ब्लेयर :: वाइपर द्वीप : ?',
      optionsEn: ['South Andaman', 'North Andaman', 'Car Nicobar', 'Great Nicobar'],
      optionsHi: ['दक्षिण अंडमान', 'उत्तरी अंडमान', 'कार निकोबार', 'ग्रेट निकोबार'],
      correctIndex: 0,
      explanationEn: 'Viper Island, known for its historic gallows built by the British before Cellular Jail, is located in the Port Blair harbor region in South Andaman district.',
      explanationHi: 'वाइपर द्वीप ऐतिहासिक फांसी घर के लिए जाना जाता है और दक्षिण अंडमान जिले में पोर्ट ब्लेयर बंदरगाह के निकट स्थित है।',
      year: 'A&N Police SI 2023',
      difficulty: 'Easy',
    ),

    // 13. English - Idioms
    const Question(
      id: 'q_eng_01',
      subjectId: 'sub_english',
      topicId: 'top_eng_idioms',
      examTags: ['CGL', 'CHSL', 'MTS'],
      questionEn: 'Select the most appropriate meaning of the idiom: "At sea"',
      questionHi: 'मुहावरे "At sea" का सबसे उपयुक्त अर्थ चुनें:',
      optionsEn: ['Travelling on an ocean voyage', 'Completely confused or lost', 'Swimming near the shore', 'Feeling wealthy and content'],
      optionsHi: ['समुद्री यात्रा पर होना', 'पूरी तरह से भ्रमित या असमंजस में', 'तट के पास तैरना', 'समृद्ध और संतुष्ट महसूस करना'],
      correctIndex: 1,
      explanationEn: 'The idiom "at sea" means to be thoroughly confused, bewildered, or unsure what to do.',
      explanationHi: '"At sea" का अर्थ होता है पूरी तरह असमंजस या भ्रम की स्थिति में होना।',
      year: 'SSC CGL 2024',
      difficulty: 'Easy',
    ),

    // 14. GA - Indian Polity
    const Question(
      id: 'q_ga_01',
      subjectId: 'sub_ga',
      topicId: 'top_ga_polity',
      examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
      questionEn: 'Under the jurisdiction of which High Court does the Union Territory of Andaman and Nicobar Islands fall?',
      questionHi: 'अंडमान और निकोबार द्वीप समूह केंद्र शासित प्रदेश किस उच्च न्यायालय के क्षेत्राधिकार में आता है?',
      optionsEn: ['Madras High Court', 'Calcutta High Court', 'Delhi High Court', 'Odisha High Court'],
      optionsHi: ['मद्रास उच्च न्यायालय', 'कलकत्ता उच्च न्यायालय', 'दिल्ली उच्च न्यायालय', 'ओडिशा उच्च न्यायालय'],
      correctIndex: 1,
      explanationEn: 'The Calcutta High Court exercises jurisdiction over the Union Territory of Andaman and Nicobar Islands through a permanent Circuit Bench located at Port Blair.',
      explanationHi: 'कलकत्ता उच्च न्यायालय पोर्ट ब्लेयर में एक स्थायी सर्किट बेंच के माध्यम से अंडमान और निकोबार द्वीप समूह पर क्षेत्राधिकार का प्रयोग करता है।',
      year: 'SSC CGL 2023',
      difficulty: 'Easy',
    ),
  ];

  static List<MockTest> get mockTests => [
    const MockTest(
      id: 'mock_chsl_01',
      title: 'A&N CHSL Full Mock Test 01',
      examCode: 'CHSL',
      durationMinutes: 60,
      totalQuestions: 100,
      totalMarks: 200.0,
      negativeMarks: 0.50,
      attemptsCount: 1284,
      isFree: true,
      isLive: false,
      sections: [
        TestSection(
          id: 'sec_chsl_reasoning',
          name: 'General Intelligence',
          hindiName: 'तार्किक योग्यता',
          questionIds: ['q_reason_01', 'q_reason_02'],
        ),
        TestSection(
          id: 'sec_chsl_ga',
          name: 'General Awareness & A&N GK',
          hindiName: 'सामान्य जागरूकता एवं अंडमान ज्ञान',
          questionIds: ['q_an_01', 'q_an_02', 'q_an_03', 'q_an_04', 'q_an_05', 'q_an_06', 'q_an_07', 'q_an_08', 'q_ga_01'],
        ),
        TestSection(
          id: 'sec_chsl_math',
          name: 'Quantitative Aptitude',
          hindiName: 'मात्रात्मक अभिरुचि',
          questionIds: ['q_quant_01', 'q_quant_02'],
        ),
        TestSection(
          id: 'sec_chsl_eng',
          name: 'English Language',
          hindiName: 'अंग्रेजी भाषा',
          questionIds: ['q_eng_01'],
        ),
      ],
    ),

    const MockTest(
      id: 'mock_cgl_01',
      title: 'A&N CGL Tier I Full Mock Test 01',
      examCode: 'CGL',
      durationMinutes: 60,
      totalQuestions: 100,
      totalMarks: 200.0,
      negativeMarks: 0.50,
      attemptsCount: 2410,
      isFree: true,
      isLive: false,
      sections: [
        TestSection(
          id: 'sec_cgl_reasoning',
          name: 'Reasoning',
          hindiName: 'तर्कशक्ति',
          questionIds: ['q_reason_01', 'q_reason_02'],
        ),
        TestSection(
          id: 'sec_cgl_ga',
          name: 'General Awareness',
          hindiName: 'सामान्य ज्ञान',
          questionIds: ['q_an_01', 'q_an_02', 'q_an_03', 'q_an_07', 'q_ga_01'],
        ),
        TestSection(
          id: 'sec_cgl_math',
          name: 'Mathematics',
          hindiName: 'गणित',
          questionIds: ['q_quant_01', 'q_quant_02'],
        ),
        TestSection(
          id: 'sec_cgl_eng',
          name: 'English Comprehension',
          hindiName: 'अंग्रेजी',
          questionIds: ['q_eng_01'],
        ),
      ],
    ),

    const MockTest(
      id: 'mock_police_01',
      title: 'A&N Police Constable Mock Test 01',
      examCode: 'POLICE',
      durationMinutes: 90,
      totalQuestions: 100,
      totalMarks: 100.0,
      negativeMarks: 0.25,
      attemptsCount: 950,
      isFree: true,
      isLive: false,
      sections: [
        TestSection(
          id: 'sec_pol_gk',
          name: 'A&N GK & General Knowledge',
          hindiName: 'अंडमान सामान्य ज्ञान एवं सामान्य अध्ययन',
          questionIds: ['q_an_01', 'q_an_02', 'q_an_03', 'q_an_05', 'q_an_06', 'q_an_08'],
        ),
        TestSection(
          id: 'sec_pol_math',
          name: 'Elementary Mathematics',
          hindiName: 'प्रारंभिक गणित',
          questionIds: ['q_quant_01', 'q_quant_02'],
        ),
        TestSection(
          id: 'sec_pol_reason',
          name: 'Analytical Ability',
          hindiName: 'विश्लेषणात्मक क्षमता',
          questionIds: ['q_reason_01', 'q_reason_02'],
        ),
      ],
    ),

    const MockTest(
      id: 'mock_live_01',
      title: 'All-Islands Mega Live Mock 2026',
      examCode: 'CGL',
      durationMinutes: 60,
      totalQuestions: 100,
      totalMarks: 200.0,
      negativeMarks: 0.50,
      attemptsCount: 3820,
      isFree: true,
      isLive: true,
      sections: [
        TestSection(
          id: 'sec_live_reason',
          name: 'General Intelligence',
          hindiName: 'तार्किक योग्यता',
          questionIds: ['q_reason_01', 'q_reason_02'],
        ),
        TestSection(
          id: 'sec_live_ga',
          name: 'General Awareness',
          hindiName: 'सामान्य ज्ञान',
          questionIds: ['q_an_01', 'q_an_02', 'q_an_03', 'q_an_04', 'q_an_07'],
        ),
        TestSection(
          id: 'sec_live_math',
          name: 'Quantitative Aptitude',
          hindiName: 'मात्रात्मक अभिरुचि',
          questionIds: ['q_quant_01', 'q_quant_02'],
        ),
        TestSection(
          id: 'sec_live_eng',
          name: 'English',
          hindiName: 'अंग्रेजी',
          questionIds: ['q_eng_01'],
        ),
      ],
    ),

    const MockTest(
      id: 'mock_pyq_01',
      title: 'A&N Administration Previous Year Paper 2024',
      examCode: 'CHSL',
      durationMinutes: 60,
      totalQuestions: 100,
      totalMarks: 200.0,
      negativeMarks: 0.50,
      attemptsCount: 1650,
      isFree: true,
      isLive: false,
      isPreviousYear: true,
      sections: [
        TestSection(
          id: 'sec_pyq_ga',
          name: 'General Awareness & Island GK',
          hindiName: 'सामान्य ज्ञान एवं द्वीप सामान्य अध्ययन',
          questionIds: ['q_an_01', 'q_an_03', 'q_an_05', 'q_an_06', 'q_an_08', 'q_ga_01'],
        ),
        TestSection(
          id: 'sec_pyq_quant',
          name: 'Quantitative Aptitude',
          hindiName: 'मात्रात्मक अभिरुचि',
          questionIds: ['q_quant_01', 'q_quant_02'],
        ),
        TestSection(
          id: 'sec_pyq_reason',
          name: 'Reasoning',
          hindiName: 'तर्कशक्ति',
          questionIds: ['q_reason_01', 'q_reason_02'],
        ),
        TestSection(
          id: 'sec_pyq_eng',
          name: 'English Language',
          hindiName: 'अंग्रेजी भाषा',
          questionIds: ['q_eng_01'],
        ),
      ],
    ),
  ];

  static Question get questionOfTheDay => const Question(
    id: 'qotd_today',
    subjectId: 'sub_an_gk',
    topicId: 'top_an_geography',
    examTags: ['CGL', 'CHSL', 'POLICE', 'MTS'],
    questionEn: 'Which island in the Andaman group is famous for its unique Limestone Caves and Mud Volcanoes?',
    questionHi: 'अंडमान समूह का कौन सा द्वीप अपनी अनूठी चूना पत्थर की गुफाओं और मिट्टी के ज्वालामुखियों के लिए प्रसिद्ध है?',
    optionsEn: ['Havelock Island (Swaraj Dweep)', 'Baratang Island', 'Neil Island (Shaheed Dweep)', 'Ross Island'],
    optionsHi: ['हैवलॉक द्वीप (स्वराज द्वीप)', 'बाराटांग द्वीप', 'नील द्वीप (शहीद द्वीप)', 'रॉस द्वीप'],
    correctIndex: 1,
    explanationEn: 'Baratang Island, situated between South and Middle Andaman, is internationally famous for its natural limestone caves, mangrove creeks, and mud volcanoes.',
    explanationHi: 'बाराटांग द्वीप, दक्षिण और मध्य अंडमान के बीच स्थित है, जो अपनी प्राकृतिक चूना पत्थर की गुफाओं और मिट्टी के ज्वालामुखियों के लिए प्रसिद्ध है।',
    year: 'A&N Daily Challenge 2026',
    difficulty: 'Medium',
  );
}
